# -*- coding: utf-8 -*-
"""VAE_gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11vzh8UUVHXqOZ8ZLW22ugoyrb49UheHZ
"""
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt

class VAE(nn.Module):
    def __init__(self, latent_dim=128):
        super(VAE, self).__init__()
        self.latent_dim = latent_dim

        # Encoder: 3x32x32 -> Latent Space
        self.encoder = nn.Sequential(
            nn.Conv2d(3, 6, kernel_size=4, stride=2, padding=1),  # 128
            nn.ReLU(),
            nn.Conv2d(6, 12, kernel_size=4, stride=2, padding=1),  # 64
            nn.ReLU(),
            nn.Conv2d(12, 24, kernel_size=4, stride=2, padding=1),  # 32
            nn.ReLU(),
            nn.Conv2d(24, 48, kernel_size=4, stride=2, padding=1),  # 16
            nn.ReLU(),
            nn.Conv2d(48, 96, kernel_size=4, stride=2, padding=1), # 8x8
            nn.ReLU(),
            nn.Conv2d(96, 192, kernel_size=4, stride=2, padding=1), # 4x4
            nn.ReLU(),
            nn.Flatten()
        )

        # Latente Parameter
        self.fc_mu = nn.Sequential(
            nn.Linear(192 * 4 * 4, latent_dim),
            nn.ReLU(),
            nn.Linear(latent_dim, latent_dim),
        )
        self.fc_logvar = nn.Sequential(
            nn.Linear(192 * 4 * 4, latent_dim),
            nn.ReLU(),
            nn.Linear(latent_dim, latent_dim),
        )

        # Decoder: Latent Space -> 3x32x32
        self.decoder_input = nn.Sequential(
            nn.Linear(latent_dim, latent_dim),
            nn.ReLU(),
            nn.Linear(latent_dim, 192 * 4 * 4),
        )

        self.decoder = nn.Sequential(
            nn.Unflatten(1, (192, 4, 4)),
            nn.ConvTranspose2d(192, 96, kernel_size=4, stride=2, padding=1), # 8x8
            nn.ReLU(),
            nn.ConvTranspose2d(96, 48, kernel_size=4, stride=2, padding=1),  # 16
            nn.ReLU(),
            nn.ConvTranspose2d(48, 24, kernel_size=4, stride=2, padding=1),  # 32
            nn.ReLU(),
            nn.ConvTranspose2d(24, 12, kernel_size=4, stride=2, padding=1),  # 64
            nn.ReLU(),
            nn.ConvTranspose2d(12, 6, kernel_size=4, stride=2, padding=1),  # 128
            nn.ReLU(),
            nn.ConvTranspose2d(6, 3, kernel_size=4, stride=2, padding=1),  # 256
            nn.Sigmoid() # Pixelwerte zwischen 0 und 1
        )

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        return mu + eps * std

    def decode(self, z):
      out = self.decoder_input(z)
      out = self.decoder(out)
      return out

    def forward(self, x):
        x = self.encoder(x)
        mu = self.fc_mu(x)
        logvar = self.fc_logvar(x)
        z = self.reparameterize(mu, logvar)
        return self.decode(z), mu, logvar

def loss_function(beta, recon_x, x, mu, logvar):
    # MSE eignet sich gut für RGB-Rekonstruktionen
    recon_loss = F.mse_loss(recon_x, x, reduction='sum')

    # KL-Divergenz Formel für Normalverteilungen
    kld_loss = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())

    return recon_loss + beta * kld_loss, recon_loss, kld_loss

import os
from PIL import Image
from torch.utils.data import Dataset

class NoClassImageDataset(Dataset):
    def __init__(self, root_dir, transform=None, max_images=np.inf):
        self.root_dir = root_dir
        self.transform = transform
        self.image_files = []
        # List all files in the root_dir and filter for common image extensions
        for filename in os.listdir(root_dir):
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp', '.tiff')):
                self.image_files.append(os.path.join(root_dir, filename))
            if len(self.image_files) > max_images:
                break
        if not self.image_files:
            raise RuntimeError(f"Found 0 image files in {root_dir}. Please ensure the directory contains images.")

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img_path = self.image_files[idx]
        image = Image.open(img_path).convert('RGB') # Ensure 3 channels

        if self.transform:
            image = self.transform(image)
        return image

from torch.utils.data import DataLoader
from torchvision import datasets, transforms

# Define transformations for the images
hin_transforms = transforms.Compose([
    transforms.ToTensor() # Convert PIL Image to PyTorch Tensor
])

# Load the dataset from a folder (assuming images are in a folder named 'data' in the content directory)
# You might need to upload your image folder to /content/data or specify the correct path
dataset = NoClassImageDataset("C:\\Datasets\\faces\\resized", hin_transforms)

# Create a DataLoader
batch_size = 64 # You can adjust this batch size
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
latent_dim = 100
betas = np.concatenate((np.linspace(0,127/99,25), np.array([127/99] * 75))) # Found by beta_vae_select.py

l = len(dataloader)

model = VAE(latent_dim=latent_dim).to(device)
model_path = "beta_vae.pth"
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

vae_losses = []
vae_grad_norms = []
vae_cos_sims = []
previous_epoch_grad_sum_flat = None

for ep in range(100):

    epoch_loss_sum = 0.0
    current_epoch_grad_sum_flat = None

    for i, batch in enumerate(dataloader):

        print(i/l)

        model.train()
        data = batch.to(device)
        optimizer.zero_grad()

        recon_batch, mu, logvar = model(data)
        loss, recon_loss, kld_loss = loss_function(betas[ep], recon_batch, data, mu, logvar)

        loss.backward()
        epoch_loss_sum += loss.item()

        # Collect gradients for this batch before optimizer step
        current_grads = [p.grad.view(-1) for p in model.parameters() if p.grad is not None]
        if current_grads:
            batch_grad_flat = torch.cat(current_grads)
            if current_epoch_grad_sum_flat is None:
                current_epoch_grad_sum_flat = batch_grad_flat.detach().clone()
            else:
                current_epoch_grad_sum_flat += batch_grad_flat.detach().clone()

    optimizer.step()

    avg_epoch_loss = epoch_loss_sum / len(dataloader)
    vae_losses.append(avg_epoch_loss)

    print(f"Epoch [{ep + 1}/1000], Avg Loss: {avg_epoch_loss:.4f}, Recon Loss: {recon_loss.item():.4f}, KLD Loss: {kld_loss.item():.4f}")

    if current_epoch_grad_sum_flat is not None:
        epoch_total_norm = current_epoch_grad_sum_flat.norm(2)
        vae_grad_norms.append(epoch_total_norm.item())

        if previous_epoch_grad_sum_flat is not None:
            cosine_similarity = F.cosine_similarity(current_epoch_grad_sum_flat, previous_epoch_grad_sum_flat, dim=0)
            vae_cos_sims.append(cosine_similarity.item())

        previous_epoch_grad_sum_flat = current_epoch_grad_sum_flat.detach().clone()

    number_tests = 2
    z = torch.randn((number_tests, latent_dim)).to(device)
    imgs = model.decode(z).detach().cpu().numpy().transpose(0, 2, 3, 1)
    import matplotlib.pyplot as plt

    for i in range(number_tests):
        plt.title(f"Epoch {ep}")
        plt.imshow(imgs[i])
        plt.show()

plt.plot(range(len(vae_losses)), vae_losses)
plt.title("VAE Losses")
plt.savefig("beta-vae_losses.png")
plt.show()

plt.plot(range(len(vae_grad_norms)), vae_grad_norms)
plt.title("VAE Grad Norms")
plt.savefig("beta-vae_grad_norms.png")
plt.show()

plt.plot(range(len(vae_cos_sims)), vae_cos_sims)
plt.title("VAE Cos Sims")
plt.savefig("beta-vae_cos_sims.png")
plt.show()